site_name: My Brain
nav:
    - Home: index.md
    - Frontend:
        - frontend/index.md
        - React:
            - Components: frontend/react/components.md
        - Nextjs:
            - Routing: frontend/nextjs/routing.md
theme:
    name: material
    font:
        text: Inter
    languages: fr
    features:
        - search.suggest
        - search.highlight
        - navigation.instant
        - navigation.indexes
        - navigation.tabs
        - header.autohide
extra_css:
  - stylesheets/style.css
plugins:
    - search:
        lang:
            - fr
            - en
