site_name: Brain
site_author: Lionel Pinheiro Duarte
site_url: https://lionelpinheiroduarte.github.io/brain/
repo_url: https://github.com/lionelpinheiroduarte/brain
repo_name: lionelpinheiroduarte/brain

nav:
    - Home: index.md
    - Reseau:
        - network/index.md
    - Windows:
        - windows/index.md
        - Windows Server: windows/windowsserver.md
theme:
    name: material
    font:
        text: Poppins 
    languages: fr
    palette:
        primary: white
    features:
        - search.suggest
        - search.highlight
        - navigation.instant
        - navigation.tabs
        - navigation.path
        - navigation.top
        - toc.follow
        - toc.integrate
        - navigation.indexes
        - header.autohide
        - navigation.sections
extra_css:
  - stylesheets/style.css
plugins:
    - search:
        lang:
            - fr
            - en
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Liopin
          name: Github
