site_name: My Brain
nav:
    - Home: index.md
    - About: about.md
    - Frontend:
        - frontend/index.md
        - React:
            - Components: frontend/react/components.md
        - Nextjs: 
            - Routing: frontend/nextjs/routing.md
theme:
    name: material
    font:
        text: Montserrat
    languages: fr
    features:
        - search.suggest
        - navigation.instant
        - navigation.indexes
        - navigation.tabs
        - header.autohide
plugins:
    - tags:
        tags_file: tags.md
    - search:
        lang:
            - fr
            - en
