site_name: Brain
site_author: Lionel Pinheiro Duarte
site_url: https://lionelpinheiroduarte.github.io/brain/
repo_url: https://github.com/lionelpinheiroduarte/brain
repo_name: lionelpinheiroduarte/brain/

nav:
    - Acceuil: 
        - index.fr.md
        - Ranking: ./home/notation.fr.md
    - Base de donnée:
        - database/index.md
        - SQL: database/sql/sql.md
    - Linux:
        - linux/linux.fr.md
    - Réseau:
        - network/index.fr.md
        - Réseau: network/networking.fr.md
    - DevOps:
        - devops/index.en.md
theme:
    name: material
    font:
        text: Poppins 
    languages: en
    palette:
        primary: white
    features:
        - search.suggest
        - search.highlight
        - navigation.tabs
        - navigation.path
        - navigation.top
        - toc.follow
        - toc.integrate
        - navigation.indexes
        - header.autohide
        - navigation.sections
        - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - stylesheets/style.css
plugins:
    - search:
        lang:
            - fr
            - en
    - i18n:
        languages:
        - locale: fr
          name: Français
          build: true
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Home: 
              - index.en.md
              - Ranking: ./home/ranking.en.md
            - Database: 
              - database/index.en.md
              - SQL: database/sql/sql.en.md
            - Linux:
              - Linux: linux/linux.en.md
              - LPI Essentials: linux/LPI_Essentials.en.md
            - Networking:
              - network/index.en.md
              - Networking: network/networking.en.md
            - DevOps:
              - devops/index.en.md
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/lionelpinheiroduarte
          name: github
