site_name: Brain
site_author: Lionel Pinheiro Duarte
site_url: https://lionelpinheiroduarte.github.io/brain/frontend/
repo_url: https://github.com/lionelpinheiroduarte/brain
repo_name: lionelpinheiroduarte/brain

nav:
    - Home: index.md
    - Frontend:
        - frontend/index.md
    - Backend:
        - backend/index.md
    - Reseau:
        - reseau/index.md
theme:
    name: material
    font:
        text: Inter
    languages: fr
    palette:
        primary: white
    features:
        - search.suggest
        - search.highlight
        - navigation.instant
        - navigation.tabs
        - navigation.path
        - navigation.top
        - toc.follow
        - toc.integrate
        - navigation.indexes
        - header.autohide
        - navigation.sections
extra_css:
  - stylesheets/style.css
plugins:
    - search:
        lang:
            - fr
            - en
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Liopin
          name: Github
