site_name: My Brain
nav:
    - Home: index.md
    - About: about.md
    - Frontend: ./frontend/react.md
      # - ./frontend/nextjs.md
theme:
    name: material
    font:
        text: Montserrat
    languages: fr
    features:
        - search.suggest
        - navigation.instant
        - navigation.indexes
        - navigation.tabs
        - header.autohide
plugins:
    - tags:
        tags_file: tags.md
    - search:
        lang:
            - fr
            - en
